## Bulding custom classifier

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [2]:
data = pd.DataFrame([("i love spending time with my friends and family", "positive"),
                     ("that was the best meal i've ever had in my life", "positive"),
                     ("i feel so grateful for everything i have in my life", "positive"),
                     ("i received a promotion at work and i couldn't be happier", "positive"),
                     ("watching a beautiful sunset always fills me with joy", "positive"),
                     ("my partner surprised me with a thoughtful gift and it made my day", "positive"),
                     ("i am so proud of my daughter for graduating with honors", "positive"),
                     ("listening to my favorite music always puts me in a good mood", "positive"),
                     ("i love the feeling of accomplishment after completing a challenging task", "positive"),
                     ("i am excited to go on vacation next week", "positive"),
                     ("i feel so overwhelmed with work and responsibilities", "negative"),
                     ("the traffic during my commute is always so frustrating", "negative"),
                     ("i received a parking ticket and it ruined my day", "negative"),
                     ("i got into an argument with my partner and we're not speaking", "negative"),
                     ("i have a headache and i feel terrible", "negative"),
                     ("i received a rejection letter for the job i really wanted", "negative"),
                     ("my car broke down and it's going to be expensive to fix", "negative"),
                     ("i'm feeling sad because i miss my friends who live far away", "negative"),
                     ("i'm frustrated because i can't seem to make progress on my project", "negative"),
                     ("i'm disappointed because my team lost the game", "negative")
                    ],
                    columns=['text', 'sentiment'])

In [3]:
data.head()

                                                text sentiment
0    i love spending time with my friends and family  positive
1    that was the best meal i've ever had in my life  positive
2  i feel so grateful for everything i have in my...  positive
3  i received a promotion at work and i couldn't ...  positive
4  watching a beautiful sunset always fills me wi...  positive

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       20 non-null     object
 1   sentiment  20 non-null     object
dtypes: object(2)
memory usage: 452.0+ bytes

In [5]:
data = data.sample(frac=1).reset_index(drop=True)

In [9]:
print(data)
data.info()

                                                 text sentiment
0   watching a beautiful sunset always fills me wi...  positive
1               i have a headache and i feel terrible  negative
2   listening to my favorite music always puts me ...  positive
3   my car broke down and it's going to be expensi...  negative
4      i'm disappointed because my team lost the game  negative
5            i am excited to go on vacation next week  positive
6   i feel so grateful for everything i have in my...  positive
7   i received a promotion at work and i couldn't ...  positive
8   i'm frustrated because i can't seem to make pr...  negative
9   i am so proud of my daughter for graduating wi...  positive
10    i love spending time with my friends and family  positive
11  my partner surprised me with a thoughtful gift...  positive
12  i feel so overwhelmed with work and responsibi...  negative
13  the traffic during my commute is always so fru...  negative
14   i received a parking ticket and it ruined my day  negative
15  i got into an argument with my partner and we'...  negative
16  i received a rejection letter for the job i re...  negative
17    that was the best meal i've ever had in my life  positive
18  i'm feeling sad because i miss my friends who ...  negative
19  i love the feeling of accomplishment after com...  positive
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       20 non-null     object
 1   sentiment  20 non-null     object
dtypes: object(2)
memory usage: 452.0+ bytes

In [8]:
X = data['text']
y = data['sentiment']

In [10]:
# text vectorization to bow - CountVectorizer
countvec = CountVectorizer()
countvec_fit = countvec.fit_transform(X)
bag_of_words = pd.DataFrame(countvec_fit.toarray(), columns = countvec.get_feature_names_out())

In [11]:
bag_of_words

,accomplishment,after,always,am,an,and,argument,at,away,be,...,vacation,ve,wanted,was,watching,we,week,who,with,work
0,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
10,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
11,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
12,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
13,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,1,0,0,1,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
19,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
# split into train and test data
X_train, X_test, y_train, y_test = train_test_split(bag_of_words, y, test_size=0.3, random_state = 7)

### Logistic Regression

In [13]:
lr = LogisticRegression(random_state=1).fit(X_train, y_train)

In [14]:
y_pred_lr = lr.predict(X_test)

In [15]:
accuracy_score(y_pred_lr, y_test)

0.16666666666666666

In [16]:
y_pred_lr

array(['negative', 'negative', 'negative', 'negative', 'negative',
       'negative'], dtype=object)

In [17]:
y_test

1     negative
17    positive
2     positive
5     positive
11    positive
0     positive
Name: sentiment, dtype: object

In [18]:
print(classification_report(y_test, y_pred_lr, zero_division=0))

              precision    recall  f1-score   support

    negative       0.17      1.00      0.29         1
    positive       0.00      0.00      0.00         5

    accuracy                           0.17         6
   macro avg       0.08      0.50      0.14         6
weighted avg       0.03      0.17      0.05         6

### Naive Bayes

In [19]:
from sklearn.naive_bayes import MultinomialNB

In [20]:
nb = MultinomialNB().fit(X_train, y_train)

In [21]:
y_pred_nb = nb.predict(X_test)

In [22]:
accuracy_score(y_pred_nb, y_test)

0.3333333333333333

In [23]:
print(classification_report(y_test, y_pred_nb, zero_division=0))

              precision    recall  f1-score   support

    negative       0.00      0.00      0.00         1
    positive       0.67      0.40      0.50         5

    accuracy                           0.33         6
   macro avg       0.33      0.20      0.25         6
weighted avg       0.56      0.33      0.42         6

### Linear Support Vector Machine

In [24]:
from sklearn.linear_model import LogisticRegression, SGDClassifier

In [25]:
svm = SGDClassifier().fit(X_train, y_train)
# possible hyper params, loss function, regularization

In [26]:
y_pred_svm = svm.predict(X_test)

In [27]:
accuracy_score(y_pred_svm, y_test)

0.16666666666666666

In [28]:
print(classification_report(y_test, y_pred_svm, zero_division=0))

              precision    recall  f1-score   support

    negative       0.17      1.00      0.29         1
    positive       0.00      0.00      0.00         5

    accuracy                           0.17         6
   macro avg       0.08      0.50      0.14         6
weighted avg       0.03      0.17      0.05         6